// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rocRcpp
Rcpp::List rocRcpp(Rcpp::LogicalVector truth, Rcpp::NumericVector output, int n_levels);
RcppExport SEXP _pvmcomparison_rocRcpp(SEXP truthSEXP, SEXP outputSEXP, SEXP n_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type output(outputSEXP);
    Rcpp::traits::input_parameter< int >::type n_levels(n_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(rocRcpp(truth, output, n_levels));
    return rcpp_result_gen;
END_RCPP
}
// updateSmallestLambda
Rcpp::NumericVector updateSmallestLambda(Rcpp::NumericVector lowest_lambda, int n_drugs, int event_id, double lambda, Rcpp::NumericVector beta);
RcppExport SEXP _pvmcomparison_updateSmallestLambda(SEXP lowest_lambdaSEXP, SEXP n_drugsSEXP, SEXP event_idSEXP, SEXP lambdaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lowest_lambda(lowest_lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type n_drugs(n_drugsSEXP);
    Rcpp::traits::input_parameter< int >::type event_id(event_idSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(updateSmallestLambda(lowest_lambda, n_drugs, event_id, lambda, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pvmcomparison_rocRcpp", (DL_FUNC) &_pvmcomparison_rocRcpp, 3},
    {"_pvmcomparison_updateSmallestLambda", (DL_FUNC) &_pvmcomparison_updateSmallestLambda, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pvmcomparison(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
